# docker-compose -f docker-compose.dev.yml up --watch

version: "3.8"
services:
  # dcs-postgres:
  #   image: postgres:15.3-alpine
  #   container_name: dcs-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  # dcs-pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: dcs-pgadmin
  #   restart: always
  #   depends_on:
  #     - dcs-postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@localhost.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./data/pgadmin:/var/lib/pgadmin
  dcs-nest-backend:
    container_name: dcs-nest-backend
    build: . # pasta do dockerfile
    ports:
      - 8080:8080
    develop: # Funcionalidades de dev
      watch: # hot reload configs
        - action: sync
          path: . # pasta raíz do host
          target: /app # pasta raíz do container
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

networks:
  default:
    name: local-network
    external: true